// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw2ANTHWmOGmJ0BJxahhCauIDOM_xC7FI',
    appId: '1:376119255208:web:d41c1d95ce3f9cb657229d',
    messagingSenderId: '376119255208',
    projectId: 'visualdsa-17626',
    authDomain: 'visualdsa-17626.firebaseapp.com',
    storageBucket: 'visualdsa-17626.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfWckvMLqOJchyLMymhAVr6Uo7N7mHI10',
    appId: '1:376119255208:android:a8b5ab8e4bb206c357229d',
    messagingSenderId: '376119255208',
    projectId: 'visualdsa-17626',
    storageBucket: 'visualdsa-17626.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEmkukb-aVEwc2h29uqyHupnRjpzvz_WI',
    appId: '1:376119255208:ios:73432685d9a4fb8a57229d',
    messagingSenderId: '376119255208',
    projectId: 'visualdsa-17626',
    storageBucket: 'visualdsa-17626.firebasestorage.app',
    iosBundleId: 'com.example.visualdsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEmkukb-aVEwc2h29uqyHupnRjpzvz_WI',
    appId: '1:376119255208:ios:73432685d9a4fb8a57229d',
    messagingSenderId: '376119255208',
    projectId: 'visualdsa-17626',
    storageBucket: 'visualdsa-17626.firebasestorage.app',
    iosBundleId: 'com.example.visualdsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw2ANTHWmOGmJ0BJxahhCauIDOM_xC7FI',
    appId: '1:376119255208:web:d5b613aa3516b88057229d',
    messagingSenderId: '376119255208',
    projectId: 'visualdsa-17626',
    authDomain: 'visualdsa-17626.firebaseapp.com',
    storageBucket: 'visualdsa-17626.firebasestorage.app',
  );
}
